### ISSUE TITLE
Small render issue for submenu counters

### ISSUE THREAD

**Issue by Yakulu** [Openworx/backend_theme#1]
First : thanks for your awesome work.
It is very valuable to get this backend theme for community version.

I got a little rendering bug for number badges on secondary menus. It will be clearer with an image :

![tableau de bord - odoo - mozilla firefox_2016-10-18_06 44 20_001](https://cloud.githubusercontent.com/assets/364212/19464675/8a775eba-94fe-11e6-956d-e285207e047e.png)

**Comment by mgielissen** [comment]
![screenshot-10 0 10 143 8069 2016-10-30 01-36-11](https://cloud.githubusercontent.com/assets/7700396/19833423/5431fc7e-9e41-11e6-8d5c-d180b8145518.png)

@-moz-document url-prefix() {
    .badge {
        margin-top: -20px;
    }
}
