### ISSUE TITLE
Some Icons missing

### ISSUE THREAD

**Issue by mareban** [Openworx/backend_theme#18]
Hello,

Great theme !

But some icons is missing !!

We are using Odoo10 in french ! 

Any ideas pls ?

Thx

**Comment by mgielissen** [comment]
When an app has no image, an empty white icon is shown.

**Comment by mareban** [comment]
Hello,

All the apps have icons :-) but when i look into DB, the web_icon is empty !!
If i try to update the record manually to specify the icon.png, the empty white icon is always displayed even after restarting odoo, clean cache, ... !!!

I've tried to reinstall all the modules having empty white icon too !

I've updated the module with the latest one version !!

Any idea  please ?

Thanks for your help


![image](https://user-images.githubusercontent.com/11810873/31818853-2a134a30-b59a-11e7-9a17-31c1c3e2af8a.png)
