### ISSUE TITLE
Submit your changes to web_responsive

### ISSUE THREAD

**Issue by lasley** [Openworx/backend_theme#21]
Hi - Happy to see you're getting good use from [`web_reponsive`](https://github.com/OCA/web/tree/10.0/web_responsive)!

I noticed that you've made some changes that would be most welcome in the base module. Do you have any thoughts to submitting these upstream?

**Comment by rafaelbn** [comment]
Hi @mgielissen , is this an option for you? We could try to help you

**Comment by lasley** [comment]
Yeah I'm actually quite curious why the code was included here instead of just depending on the `web_responsive` module? I specifically designed things to be quite modular, with theming use case at the forefront of thought.

**Comment by mgielissen** [comment]
There where a lot of changes (and way faster to implement), that's the reason the code was included instead of depending on the module. Maybe the code can depend on the module, but that will take some time to investigate. So any help is welcome.

**Comment by lasley** [comment]
I'm not willing to put forth effort to a project that hides authorship (#22). Sorry

**Comment by mgielissen** [comment]
The theme now depends on web_responsive. https://github.com/Openworx/backend_theme/commit/6b2f2ba31b9a82aec31910d998299c90218c4691

**Comment by lasley** [comment]
Nice, thank you @mgielissen. It makes me happy to see that we came to a good solution here and that it didn't cost you too much dev effort.

I'll be letting the customer that noticed the module incompatibility know that they can now safely use your theme in combination with `web_responsive`.

**Comment by rafaelbn** [comment]
Thank you @mgielissen ! 😄
