### ISSUE TITLE
Prepared for v11?

### ISSUE THREAD

**Issue by melroy89** [Openworx/backend_theme#23]
Soon (October 5) Odoo 11 will be released.

Are you already testing with v11, or is the new UI now part by default in the community edition?

Thanks for this wonderful theme!

Kind regards,
Melroy vd Berg

**Comment by mgielissen** [comment]
The theme was tested with v11 a month ago and it worked fine. V11 has only a new kanban UI for now. When the beta is available, migration will be started.

**Comment by melroy89** [comment]
Nice, good to hear!

**Comment by mgielissen** [comment]
The theme for v11 is almost ready

**Comment by mgielissen** [comment]
For a demo see https://youtu.be/qkjwOSeuMTo

**Comment by melroy89** [comment]
You didn't create a new branch or something :S?

**Comment by mgielissen** [comment]
For V11? It will be published very soon.

**Comment by mgielissen** [comment]
Here is the new branch: https://github.com/Openworx/backend_theme/tree/11.0
