### ISSUE TITLE
Company name or logo?

### ISSUE THREAD

**Issue by melroy89** [Openworx/backend_theme#24]
The default template shows atleast the picture, so you know in which administration you are working.

But with this theme you don't have any hint. See before and after back-end theme v10 installation.

Before:
![before](https://user-images.githubusercontent.com/628926/31021735-fca9f742-a536-11e7-968d-40a9fe63ba2a.png)

After:
![after](https://user-images.githubusercontent.com/628926/31021734-fca78354-a536-11e7-8810-f97a7f0e4a6a.png)

Is it a good idea to add the company name or something?

Kind regards,
Melroy

**Comment by mgielissen** [comment]
Odoo Enterprise doesn't have a company logo also ;)
In a new version there will be a app side bar with logo above.

**Comment by melroy89** [comment]
Ow ;D

**Comment by mgielissen** [comment]
The latest version has now a company logo in the app dashboard.

**Comment by melroy89** [comment]
So I download the latest version to my addons directory and I get:
`2017-10-02 00:23:48,033 18113 ERROR odoo odoo.modules.graph: module backend_theme_v10: Unmet dependencies: web_responsive`

![owow](https://user-images.githubusercontent.com/628926/31060761-322ed94e-a719-11e7-8996-c6c0655a4b26.png)

Meaning the web interface was blocked. And I couldn't install this missing dependency. 

So I though I download this module as well (`web_responsive`) and try to install it via CLI (odoo -i web_responsive). That apparently didn't work either (it didn't install it, but keeps reporting about the missing module during startup). So I reverted back to the old theme version.

I tried to install it web_responsive via the web interface again, and I get:
```
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3560, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3711, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Fout bij bevestigen beperking

Element '<xpath expr="//nav[@id='oe_main_menu_navbar']">' kan niet worden gevonden in de bovenliggende weergave

Fout context:
Weergave`App Drawer - Web Client`
[view_id: 647, xml_id: n/b, model: n/b, parent_id: 173]
None" while parsing None:13, near
<data inherit_id="web.webclient_bootstrap" name="App Drawer - Web Client">
```

Using the default template/theme it works. It's unrelated to the plugin itself (web_reponsive), but using the default theme I could install first the web_responsive plugin and then your theme again.

**Comment by mgielissen** [comment]
Web_responsive is now a depency in the new version. Place this also in the addons and update the theme.
