### ISSUE TITLE
Right click on some menus/buttons doesn't recognize them as links

### ISSUE THREAD

**Issue by BeAntares** [Openworx/backend_theme#28]
Right click on some menus/buttons doesn't recognize them as links, instead of having the "Open in new tab/window" options, this is the right-click menu on Firefox, and it's similar on Chromium.

![screenshot from 2017-10-17 15-00-17](https://user-images.githubusercontent.com/12944239/31691850-59c47e5c-b34c-11e7-899c-9a019f306e85.png)

**Comment by mgielissen** [comment]
This button behaviour is also in CE without the theme installed.
