### ISSUE TITLE
Enhance no-content contrast

### ISSUE THREAD

**Issue by Yakulu** [Openworx/backend_theme#3]
A small suggestion about improving the nocontent rendering (atm low contrast) :

![selection_2016-10-30_07 14 43_001](https://cloud.githubusercontent.com/assets/364212/19834835/f0764674-9e70-11e6-92a8-f0a256b432cf.png)

The CSS class concerned is `.oe_view_nocontent` and the applied color is `@gray` (777). I suggest using `@gray-dark` (333).

Thanks for reading.

**Comment by mgielissen** [comment]
![screenshot-10 0 10 143 8069 2016-10-30 16-39-58](https://cloud.githubusercontent.com/assets/7700396/19837689/8c02b570-9ebf-11e6-9aa4-aef479cf84ee.png)

.oe_view_nocontent {
    color: #333;
}

**Comment by Yakulu** [comment]
Yes that seems better to me. What do you think ?

**Comment by mgielissen** [comment]
CSS added in 936707b
