### ISSUE TITLE
Some icons is missing

### ISSUE THREAD

**Issue by mareban** [Openworx/backend_theme#32]
Hello,

All the apps have icons :-) but when i look into DB, the web_icon is empty !!
If i try to update the record manually to specify the icon.png, the empty white icon is always displayed even after restarting odoo, clean cache, ... !!!

I've tried to reinstall all the modules having empty white icon too !

I've updated the module with the latest one version !!

Any idea please ?

Thanks for your help

![image](https://user-images.githubusercontent.com/11810873/31851447-365357d2-b666-11e7-9f65-3669928adce8.png)

**Comment by mgielissen** [comment]
The module web_responsive fetches the icon from the addon is available. If not, then you have the empty white icon. I guess the addons don't have an icon.

**Comment by mareban** [comment]
Hello,

for example : 

-rw-r--r--. 1 root root  9455 Jul 15 02:28 connector/static/description/icon.png
-rw-r--r--. 1 root root 18957 Aug 23 00:10 knowledge/static/description/icon.png
-rw-r--r--. 1 root root  1814 Sep 30  2016 maintenance/static/description/icon.png

Icons are available, but not displayed !

Is there a restriction on png file ?
Why there are not fetched and put in DB ??

Thanks for your help.

**Comment by mgielissen** [comment]
The theme depends on web_responsive module. Try removing the backend theme only and check if web_responsive shows an icon.

**Comment by mareban** [comment]
I've removed the backend_theme and icons are missing too !

So, the problem is in web_reponsive as you guessed :-) 

I'll try to look on the github issue page to see if i can find a solution for that problem !


Thanks for your help

https://github.com/OCA/web/tree/10.0

**Comment by lasley** [comment]
This is a module level thing, and doesn't have anything to do with web_responsive. The icon must also be declared in the menu item, such as [here](https://github.com/OCA/vertical-medical/pull/126/files)

**Comment by mareban** [comment]
I've had web_icon in menu.xml,  update the addons on applications menu  and now it's OK :-) 

So, no problem with the backend_theme and web_responsive !

Thank you all for your help.
