### ISSUE TITLE
[BUG] User menu not displaying in smaller screens

### ISSUE THREAD

**Issue by IOAyman** [Openworx/backend_theme#34]
## Current behavior:

The user menu -top right corner- does is not being displayed on smaller than screens (width < 768px).

![screenshot_2017-10-27_09-19-18](https://user-images.githubusercontent.com/6185849/32094978-d7119d92-bb01-11e7-81b8-f678c8034ae5.png)
![screenshot_2017-10-27_09-20-05](https://user-images.githubusercontent.com/6185849/32094981-dbc27e74-bb01-11e7-97d0-504287be98f3.png)

- - -
_Odoo version:_ 10.0
Theme branch: 10.0 at 9b3ee22

**Comment by IOAyman** [comment]
Closed by #35

**Comment by melroy89** [comment]
Same problem in 11.0 branch..

**Comment by IOAyman** [comment]
I've reopened the issue @danger89. I'll check about that and open up another PR, asap

**Comment by melroy89** [comment]
Thanks. Yea v11 will also gives:

![image](https://user-images.githubusercontent.com/628926/35001472-1d974530-fae7-11e7-878f-9de3382fd4d6.png)

**Comment by yanfrank** [comment]
Hi, when i apply   #caf86e3 on backend_theme_v11/static/src/less/style.less or CLONE REPO .git
+
+
+
+// navbar ==========================================
+
+.navbar-default .navbar-nav .open .dropdown-menu > li > a {
+  @media (max-width : @screen-xs-max) {
+    color : @brand-primary;
+    text-align: center;
+  }
+}
+

I  lost/cant see "sub-menu" on small smartphone screen. But user menu is OK.
![bluestack-chrome-invoicing-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344483-16a5149e-13e9-11e8-9b5f-5d0ef347c1cf.png)
![bluestack-chrome-settings-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344484-16c5c16c-13e9-11e8-898f-c17620a27024.png)
![opera-invoicing-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344485-16e6119c-13e9-11e8-9a64-eaf8a6abd2a9.png)
![opera-salessubmenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344486-1704e05e-13e9-11e8-9274-83996ff4f823.png)
![user-menu](https://user-images.githubusercontent.com/22683525/36344526-d6692bd0-13e9-11e8-922a-136f2f6cbf43.png)

I used Odoo 11.0-20180212 (Community Edition)
