### ISSUE TITLE
checkboxes do not display as checked

### ISSUE THREAD

**Issue by sterbhai** [Openworx/backend_theme#37]
in my case the checkboxes never get checked - is there some styles/fonts missing?
when a checkbox is clicked it just becomes a little stronger borders.

![not displaying checked](https://user-images.githubusercontent.com/8261071/32166603-a66c899c-bd66-11e7-83cf-8d0f15868f59.png)

**Comment by mgielissen** [comment]
Did you restart the Odoo service? The custom checkbox is a svg file.

**Comment by sterbhai** [comment]
You are perfectly right. After restart of the service its ok.
Thanks
