### ISSUE TITLE
Issue on tiles organization

### ISSUE THREAD

**Issue by edser-pcg** [Openworx/backend_theme#4]
There is an issue on the theme on which the second line starts at the 4th icon and after the last 3 positions of the row are filled it moves to the next one.

![image](https://cloud.githubusercontent.com/assets/6585110/20253694/29249bd0-aa04-11e6-8138-287ad649170d.png)

If more modules are installed than it still keeps those positions empty and I just noticed that it evens adds more empty positions. I have already tried it on two servers and I got the same behavior.

![image](https://cloud.githubusercontent.com/assets/6585110/20253706/45f7a734-aa04-11e6-976c-c2bb8e602145.png)

And in developer mode:

![image](https://cloud.githubusercontent.com/assets/6585110/20253813/2ad62e84-aa05-11e6-891a-7cf0afa8e149.png)

**Comment by edser-pcg** [comment]
Same thing happens on the one for v9.

**Comment by zimbora69** [comment]
:sos:

**Comment by maringuadarrama** [comment]
The problem seems to affect only when you use a language different from english,

**Comment by mgielissen** [comment]
Maybe when the text translation is longer and takes 2 lines?

**Comment by edser-pcg** [comment]
@mgielissen yes, it seems to be that it is when the text takes 2 lines. Because POS name takes 2 lines and when it is installed than the organization gets lost. When not installed everything shows correctly.

![image](https://cloud.githubusercontent.com/assets/6585110/21300725/0c62f3e0-c57d-11e6-8359-a080a378b792.png)

EDIT: Sorry but no, the issue is not because of the 2 lines text because when entering developer mode it shows the links tracker with a 2 lines text and the organization looks fine, it only happens when the POS is installed.

![image](https://cloud.githubusercontent.com/assets/6585110/21301041/1aa28026-c580-11e6-972c-72ba6fbf7ffd.png)

**Comment by mgielissen** [comment]
Fix for 2 lines titel:
.app-drawer-nav .app-drawer-title

    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;

![afbeelding](https://cloud.githubusercontent.com/assets/7700396/21945904/37b0d5a6-d9de-11e6-89f1-352cab7ef0c8.png)

**Comment by mgielissen** [comment]
Fixed in a4d78f7
