### ISSUE TITLE
[IMPROVEMENT] Add search in the main apps dashboard

### ISSUE THREAD

**Issue by melroy89** [Openworx/backend_theme#41]
Hi,

Just like the official Odoo Apps Dashboard, you can search for modules/apps/configurations within this dashboard, just by typing a string.

See this in a real world example by Nathan Moss:
https://youtu.be/4hgyHlUFeLc?t=12m21s

Wouldn't it be great to have the same feature in your backend theme as well??

Odoo version: V11

Regards,
Melroy

**Comment by mgielissen** [comment]
https://github.com/OCA/web/pull/714
