### ISSUE TITLE
Bug for #caf86e3  backend_theme_v11/static/src/less/style.less

### ISSUE THREAD

**Issue by yanfrank** [Openworx/backend_theme#50]
Hi, this is an amazing theme, i love it.
But when i apply   #caf86e3 on backend_theme_v11/static/src/less/style.less or CLONE REPO .git
Related:
https://github.com/Openworx/backend_theme/issues/34

+
+
+
+// navbar ==========================================
+
+.navbar-default .navbar-nav .open .dropdown-menu > li > a {
+  @media (max-width : @screen-xs-max) {
+    color : @brand-primary;
+    text-align: center;
+  }
+}
+

I  lost/cant see "sub-menu" on small smartphone screen. But user menu is OK.

![bluestack-chrome-invoicing-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344483-16a5149e-13e9-11e8-9b5f-5d0ef347c1cf.png)
![bluestack-chrome-settings-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344484-16c5c16c-13e9-11e8-898f-c17620a27024.png)
![opera-invoicing-submenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344485-16e6119c-13e9-11e8-9a64-eaf8a6abd2a9.png)
![opera-salessubmenu-odoo11-18-02-12](https://user-images.githubusercontent.com/22683525/36344486-1704e05e-13e9-11e8-9274-83996ff4f823.png)
![user-menu](https://user-images.githubusercontent.com/22683525/36344526-d6692bd0-13e9-11e8-922a-136f2f6cbf43.png)

I used Odoo 11.0-20180212 (Community Edition) 

Thanks for your time.

**Comment by yanfrank** [comment]
someone alive?

**Comment by cesarsc79** [comment]
someone alive?

**Comment by mgielissen** [comment]
Fixed in https://github.com/Openworx/backend_theme/commit/f7904479b114c9c46e7acfe002cfc26d0b8ca063
