### ISSUE TITLE
Mixed Content for background image after Nginx SSL setup

### ISSUE THREAD

**Issue by eversatis** [Openworx/backend_theme#55]
Letsencrypt SSL Nginx set up is all good in front end but comes Mixed Content at backend: The page at 'https://www.xxx.com/web?#id=3&view_type=form&model=res.company&action=51' was loaded over HTTPS, but requested an insecure image 'http://www.xxx.com/backend_theme_v10/static/src/img/material-background.jpg'. This content should also be served over HTTPS.

**Comment by derfl0** [comment]
You can avoid this problem by creating a proper redirect and activating the proxy_mode
https://www.odoo.com/documentation/10.0/setup/deploy.html#id7

**Comment by mgielissen** [comment]
Also check that the System Parameter: web.base.url is using https://
