### ISSUE TITLE
Migrating to Progressive Web App

### ISSUE THREAD

**Issue by emanjuGbr** [Openworx/backend_theme#59]
Hi there,

I am using your back end theme and I am very happy with it! Thanks for the great work.
I am wondering if you keep developing this theme and if you have any plans to support progressive web apps?

I think this step would be a huge benefit!
I would also consider helping out on this and follow a partner approach.

Please get in contact with me!
Thanks in advance!

**Comment by mgielissen** [comment]
The theme depends on the web_responsive module. I think most parts must be done in the web_responsive addon. Also for the upcoming Odoo 12 the development will be continued and any help is welcome!
