### ISSUE TITLE
Search Bug In App Drawer

### ISSUE THREAD

**Issue by alihusnainarshad** [Openworx/backend_theme#63]
I think Its A security problem.
**User can search all the menus** from here.
Please Guide How i can remove search from app drawer , Thanks

**Comment by alihusnainarshad** [comment]
I fixed This Issue by simply Removing Search From  App Menu . 🤣🤣🤣

**Comment by mareban** [comment]
Agree with you ! How can i remove this please ??

Thanks for your help.
