### ISSUE TITLE
the logo of a customized module is not displayed

### ISSUE THREAD

**Issue by ghost** [Openworx/backend_theme#71]
the logo of a customized module is not displayed on the main screen of odoo 
![logo-theme](https://user-images.githubusercontent.com/37008213/45269569-06daf480-b456-11e8-86c4-81a9f45dea20.png)

**Comment by mgielissen** [comment]
Here is the solution: https://www.odoo.com/forum/help-1/question/icon-not-showed-in-my-custom-app-120274
