### ISSUE TITLE
Odoo 12?

### ISSUE THREAD

**Issue by yelizariev** [Openworx/backend_theme#76]
Is there any plans to implement theme for v12? It has almost similar UI as in Odoo EE
![theme](https://user-images.githubusercontent.com/186131/46526342-6ab2da80-c8a7-11e8-89d1-724a5d43b006.png)

**Comment by mgielissen** [comment]
When the web_responsive module is migrated we can start the migration to v12.

**Comment by mgielissen** [comment]
The first version only has the app sidebar and more enterprise look'n'feel. The second version will using web_responsive when it's available.

**Comment by yelizariev** [comment]
web_responsive is just merged

**Comment by Yakulu** [comment]
I guess with 22d8dae83494d3f0978ad970873cbad6cca3a20d this issue could be closed ;)

**Comment by mgielissen** [comment]
Indeed :)
