### ISSUE TITLE
[12.0] Overlapping elements in chatter (Following/Unfollow, alarm menu, attachments)

### ISSUE THREAD

**Issue by grzekru** [Openworx/backend_theme#80]
[12.0] Overlapping elements in chatter (Following/Unfollow, alarm menu, attachments)
![image](https://user-images.githubusercontent.com/5862658/49082199-75577380-f249-11e8-929d-f7f89de61319.png)

**Comment by mgielissen** [comment]
This theme is deprecated, the new one is https://github.com/Openworx/backend_theme/tree/12.0/backend_theme_v12
