### ISSUE TITLE
Enterprise edition

### ISSUE THREAD

**Issue by philippeluickx** [Openworx/backend_theme#81]
We are looking for a theme for v11 enterprise edition. Considering there is a warning ( Backend themes might not work with Odoo Enterprise Edition. Please read the description carefully and, in doubt, ask the author before buying. ) I would like to check with you if this is supposed to work on Enterprise too?

I tried real quick and got an error
`ValueError: Element '<xpath expr="//div[hasclass('o_sub_menu')]">' cannot be located in parent view`

**Comment by mgielissen** [comment]
It works on only for community.
