### ISSUE TITLE
some kanban views are truncated

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [Openworx/backend_theme#87]
some of my kanban views are truncated.
the cards are squeezed.
Have you ever been through this?

![FireShot Capture 002 - Ponto de Venda - Odoo - jarvis](https://user-images.githubusercontent.com/12830044/57020433-9f99cc80-6bff-11e9-9c00-0363c898fc4b.png)
![FireShot Capture 003 - Projetos - Odoo - jarvis](https://user-images.githubusercontent.com/12830044/57020434-a0326300-6bff-11e9-8f64-8897ab94cf2b.png)

**Comment by mgielissen** [comment]
Please try only with web_responsive module only, so uninstall the theme and check if the problems exists with web_responsive.

**Comment by Alexandre-Bernardes** [comment]
Hi,
Thanks in advance
I tried without de backend_theme_v11, but problem persists.
Any idea?

**Comment by mgielissen** [comment]
Then the problem is related to web_responsive.
