### ISSUE TITLE
[12.0] Foot color

### ISSUE THREAD

**Issue by manuelcalerosolis** [Openworx/backend_theme#89]
It is important to change the properties of the text at the bottom of the columns, the text appears in white and does not distinguish well with the gray background.

In static/src/scss/style.scss

.o_list_view tfoot {
    background-color: $brand-primary;
    color: #ffffff;
    cursor: default;
    font-weight: bold;
}

Thank you

**Comment by mgielissen** [comment]
Which Odoo version?

**Comment by manuelcalerosolis** [comment]
12.0

**Comment by mgielissen** [comment]
The problem happens when the latest web_responsive is used.

**Comment by mgielissen** [comment]
Fixed in https://github.com/Openworx/backend_theme/commit/82c194ca863bf62e04cd5ba7ad19335e286f58b1
