### ISSUE TITLE
Checks on checkboxes not visible - Odoo 10

### ISSUE THREAD

**Issue by funcurv** [Openworx/backend_theme#9]
Hi,

running odoo 10 locally on Windows 10 Notebook for demo purposes. On checkboxes you cannot see whether they are checked or not. See attached image where customer is checked.

br

Werner

![image](https://cloud.githubusercontent.com/assets/17149532/21500560/624b2074-cc40-11e6-90f7-3d96ce445a0a.png)

**Comment by archerdx** [comment]
Also seeing this. MacOS Sierra, Chrome and Safari browsers.

**Comment by archerdx** [comment]
All right, figured out that the Odoo 10 server just needs to be restarted after installing this theme (possibly any theme with referenced web assets). The missing checkbox is called checked.svg; there's also a background image (material-background.jpg) and a font that will be found once the Odoo service is restarted.

**Comment by funcurv** [comment]
works now after restart.
thx
Werner
