### ISSUE TITLE
[Version Odoo 13] Can somenone find the sidebar settings formerly find in user preferences?

### ISSUE THREAD

**Issue by clxadmin** [Openworx/backend_theme#91]
Hello Odoo users, I'm running Odoo 13 with this backend theme and miss the sidebar settings formerly find in user preferences. Can someone find it in his installation?

![Screenshot - 2020-01-21T172744 654](https://user-images.githubusercontent.com/9445285/72824461-92cd7500-3c75-11ea-9c9a-c809d14cde0e.png)

**Comment by mgielissen** [comment]
The app sidebar is not ready for v13.
