### ISSUE TITLE
odoo 13 missing dependency error "web_responsive"

### ISSUE THREAD

**Issue by MosabWadea** [Openworx/backend_theme#92]
Hi
after installing odoo 13 and trying to install the backend_theme it is giving me an error about a missing package "ow_web_responsive" while the package name from OCA is web_responsive only..

Can you please fix that

Thanks

**Comment by mgielissen** [comment]
You can download it here https://www.odoo.com/apps/themes/13.0/backend_theme_v13/
As soon as web_responsive v13 is available in the Odoo appstore, the dependency will be changed from ow_web_responsive to web_responsive.
